### ISSUE TITLE
where to get /usr/local/bin/pairsqc/pairsqc.py

### ISSUE THREAD

**Issue by jiangshan529** [4dn-dcic/docker-4dn-hic#79]
Hi, in the "run-pairsqc-single.sh" script, there's another py file "pairsqc.py". How should I get this one? Thanks!

**Comment by jiangshan529** [comment]
It seems it is under pairix folder. I installed pairix using Anaconda, and I cannot open "anaconda/myenv/bin/pairix", it looks like this:
```
anaconda/myenv/bin $ ll -h pairix -rwxrwxr-x 2 root 85K Mar 26  2021 pairix*
```
```
cd pairix
-bash: cd: pairix: Not a directory
```

**Comment by clarabakker** [comment]
Hi Jiangshan,
From the `pairsqc-single.sh` script, you will see `pairsqc.py` comes from the `pairsqc` directory, rather than `pairix`. You can see this file and learn more here: [https://github.com/4dn-dcic/pairsqc](https://github.com/4dn-dcic/pairsqc). I hope this is helpful!

**Comment by jiangshan529** [comment]
Hello, Clara,

Thanks for your pipeline for hic analysis. Now I basically go through all
the steps and can generate .hic file from the beginning of .fastq file. But
I am not sure if restriction enzyme information was used during this
process. There are two steps that we use restriction enzyme information,
one is "run-addfrag2pairs.sh" and another is "Restriction Enzyme Check"
in 4dndcic/4dn-re-checker/v1.1. Those two steps are most like QC steps.
However, in Hic-Pro pipeline, the restriction enzyme cutting site is used
to removed some reads. So I am not sure if the restriction enzyme
information is taken into steps of 4DN-hic pipeline.

Thanks,
Jiangshan

Clara ***@***.***> 于2023年1月30日周一 12:54写道：

**Comment by clarabakker** [comment]
Hi Jiangshan,
I have just replied to your helpdesk request, but in case others look have the same question: yes. Restriction enzymes are used for contact filtering within fragments for in-situ Hi-C, dilution Hi-C, and capture Hi-C experiments. Here is our [documentation](https://data.4dnucleome.org/resources/data-analysis/hi_c-processing-pipeline#matrix-aggregation) for reference.

**Comment by jiangshan529** [comment]
Yeah, I see. I think my key point here is exactly in which step you take the restriction information into the analysis pipeline. I see it in two parts in the pipeline, but it seems there are both for QC step.

发自我的iPhone

**Comment by clarabakker** [comment]
You are correct that both of the steps mentioned do use restriction enzyme information for the purpose of QC. However, in the second half of the pipeline ([hi-c-processing-pairs](https://github.com/4dn-dcic/docker-4dn-hic/blob/master/cwl/hi-c-processing-pairs.cwl)), the [pairs2hic](https://github.com/4dn-dcic/docker-4dn-hic/blob/master/cwl/pairs2hic.cwl) step employs [Juicer pre](https://github.com/aidenlab/juicer/wiki/Pre#file-format), which does perform filtering based on restriction enzymes. It may be helpful to read more (or ask the maintainers) about both Juicer and pairsamtools, which are used throughout the pipeline, if there is a more specific kind of filtering for which you are looking!
