### ISSUE TITLE
Empty cool and mcool files

### ISSUE THREAD

**Issue by laracolombo** [4dn-dcic/docker-4dn-hic#82]
Hi! 

I am running the Hi-C Processing Pipeline on my data but I noticed some issues when generating the cool and mcool files at the matrix generation step. 
While the .hic matrix looks perfectly fine by some downstream analysis, I have noticed that both .cool and .mcool files are empty. By empty, I mean that the contact matrices stored in these formats is full of zeros or NaN. However, the matrix stored in the .hic is how I would expect it. Both matrices are generated from the same pairs file. 

Here I show the commands that I used to generate the .cool file: 

`singularity exec 4dn-hic_latest.sif cooler cload pairix -p ${THREADS} -s ${MAX_SPLIT} ${CHR_SIZE}:${BIN_SIZE} ${PAIRS} ${SAMPLE_DIR}/${SAMPLE}.cool 
`

I think the problem occurs already when generating the .cool file in the very first step as it immediately results to be empty, I checked its emptiness by plotting the matrix as follows: 

`clr = cooler.Cooler('bin.cool')`
`mat = clr.matrix(balance=False).fetch('chr1')`
`plt.matshow(np.log10(mat), cmap='YlOrRd')`

Also, the maximum value of the matrix is a 0. 

This doesn't occur for the .hic matrix, whose plots look fine and whose matrix is not filled with 0s.

Thank you in advance for your help!

**Comment by clarabakker** [comment]
Hi Lara,
Hm, it's tough to say what is happening. Can you see any logs or output from the singularity command that could help identify the issue?

One particular issue that we've seen is that the chromsizes file needs to exist in the same directory. If you haven't, you can try copying the chromsizes over just before you run that step (as simple as `cp /path/to/chrsize_file ./tmpchrsize`). You can see slightly more context in [our cwl](https://github.com/4dn-dcic/docker-4dn-hic/blob/a0d5318c07793cb7d841387d13b026dedc7f0496/scripts/run-cooler.sh#L9) for that step, which I'm guessing you've already seen.

**Comment by nvictus** [comment]
If you are having issues with the `pairix` loader, you can also try [cload pairs](https://cooler.readthedocs.io/en/latest/cli.html#cooler-cload-pairs) which doesn't require the index file.

**Comment by laracolombo** [comment]
Hello, thank you for your replies! 
I was able to find out what the issue was: I must have compromised the index file that is needed to compute the cool matrices but not the hic matrix.
